# Generated by Django 2.0.7 on 2018-07-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Description',
            field=models.TextField(default=''),
        ),
    ]
